
##配置redis节点
spring:
  redis:
    cluster:
      nodes:
        - 10.82.0.102:7000
        - 10.82.0.102:7001
        - 10.82.0.102:7002
        - 10.82.0.102:7003
        - 10.82.0.102:7004
        - 10.82.0.102:7005
    # Redis数据库索引（默认为0）
    database: 0
    password:

# Redis服务器地址
#spring:
#  redis:
#    host: 127.0.0.1